INSERT INTO Voters (Name, HasVoted) VALUES ('Luke Skywalker', 0);
INSERT INTO Voters (Name, HasVoted) VALUES ('Darth Vader', 0);
INSERT INTO Voters (Name, HasVoted) VALUES ('Princess Leia', 0);
INSERT INTO Voters (Name, HasVoted) VALUES ('Han Solo', 0);
INSERT INTO Voters (Name, HasVoted) VALUES ('Yoda', 0);
INSERT INTO Voters (Name, HasVoted) VALUES ('Obi-Wan Kenobi', 0);
INSERT INTO Voters (Name, HasVoted) VALUES ('Chewbacca', 0);
INSERT INTO Voters (Name, HasVoted) VALUES ('R2-D2', 0);
INSERT INTO Voters (Name, HasVoted) VALUES ('C-3PO', 0);
INSERT INTO Voters (Name, HasVoted) VALUES ('Emperor Palpatine', 0);
INSERT INTO Candidates (Name, VoteCount) VALUES ('Joker', 0);
INSERT INTO Candidates (Name, VoteCount) VALUES ('Harley Quinn', 0);
INSERT INTO Candidates (Name, VoteCount) VALUES ('Penguin', 0);
INSERT INTO Candidates (Name, VoteCount) VALUES ('Riddler', 0);
INSERT INTO Candidates (Name, VoteCount) VALUES ('Two-Face', 0);
INSERT INTO Candidates (Name, VoteCount) VALUES ('Scarecrow', 0);
INSERT INTO Candidates (Name, VoteCount) VALUES ('Poison Ivy', 0);
INSERT INTO Candidates (Name, VoteCount) VALUES ('Bane', 0);
INSERT INTO Candidates (Name, VoteCount) VALUES ('Mr. Freeze', 0);